# Generated by Django 4.2.6 on 2023-10-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['-created_at']},
        ),
    ]
