# Generated by Django 4.2.6 on 2023-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMemberModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Diretor'), (2, 'Ator')])),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cast_members',
                'ordering': ['-created_at'],
            },
        ),
    ]
